# fly.toml app configuration file generated for product-aggregator on 2023-05-14T15:38:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "product-aggregator"
primary_region = "ams"

[processes]
web = "waitress-serve --port 8080 product_aggregator.wsgi:application"
worker = "python manage.py rqworker default"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8080"

[http_service]
  processes = ["web"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
